import os

TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHANNEL_ID = os.environ["TELEGRAM_CHANNEL_ID"]
TELEGRAM_PERSONAL_CHAT_ID = os.environ["TELEGRAM_PERSONAL_CHAT_ID"]

TWELVE_DATA_API_KEY = os.environ["TWELVE_DATA_API_KEY"]
SYMBOL = os.environ.get("SYMBOL", "XAU/USD")
TREND_TIMEFRAME = os.environ.get("TREND_TIMEFRAME", "4h")
ENTRY_TIMEFRAME = os.environ.get("ENTRY_TIMEFRAME", "1h")
CANDLE_LIMIT = 300

ATR_STOP_MULTIPLIER = 1.5
TP_R_MULTIPLES = [1.0, 2.0, 3.0]   # TP1, TP2, TP3 as multiples of the stop distance

MIN_SCORE_TO_SEND = 2
COOLDOWN_MINUTES = 240

TRADES_FILE = "trades.json"
